### ISSUE TITLE
 0 recovered in Some countries 

### ISSUE THREAD

**Issue by mhadji05** [Tetracyl/COVID19-App#1]
Some countries  like UK,Spain Sweden, e.t.c have always 0 recovered and this isn't true. Can you fix this problem pls?

**Comment by 3eif** [comment]
This isn't a problem with the bot. The website that the bot fetches information from has no data on recovered in some countries. https://www.worldometers.info/coronavirus/

**Comment by mhadji05** [comment]
Is there any chance that will be replaced this url and work better?
